name: CD - Deploy Model to Cloud Run

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy Model API to Cloud Run"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: sixth-utility-449722-p8

      - name: Download Model from GCS
        run: |
          gsutil cp gs://housing-data-bucket-poc/model_registry/model.pkl model.pkl

      - name: Build and Push Docker Image
        run: |
          gcloud auth configure-docker --quiet
          docker build -t gcr.io/sixth-utility-449722-p8/house-price-api:latest .
          docker push gcr.io/sixth-utility-449722-p8/house-price-api:latest

      - name: Deploy Model API to Cloud Run
        run: |
          gcloud run deploy house-price-api \
            --image gcr.io/sixth-utility-449722-p8/house-price-api:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
