name: CI - Train Model & Deploy to Cloud Run

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  train_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Load data into BigQuery
        run: |
          bq load --source_format=CSV --skip_leading_rows=1 \
              ${{ secrets.GCP_PROJECT_ID }}:housing_data.housing_table \
              gs://housing-data-bucket-poc/housing_data.csv \
              size:FLOAT,bedrooms:INTEGER,location:STRING,price:FLOAT

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install db-dtypes

      - name: Train the model
        run: python train_model.py

      - name: Authenticate Docker to GCR
        run: gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/mlops-api:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/mlops-api:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy house-price-api \
            --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/mlops-api:latest \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated

      - name: Upload Model Artifacts to Model Registry
        run: |
          gsutil cp gs://housing-data-bucket-poc/models/* gs://housing-data-bucket-poc/model_registry/
