name: CI - QA Validations and Training

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  train:
    name: "Train Model with Vertex AI Custom Job"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: sixth-utility-449722-p8

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build and Push Docker Image
        run: |
          cd train
          gcloud auth configure-docker
          docker build -t gcr.io/sixth-utility-449722-p8/house-price-training:latest .
          docker push gcr.io/sixth-utility-449722-p8/house-price-training:latest

      - name: Submit Custom Training Job to Vertex AI
        run: |
          gcloud ai custom-jobs create \
            --display-name=house-price-training \
            --region=us-central1 \
            --project=sixth-utility-449722-p8 \
            --service-account=muthuwings2poc@sixth-utility-449722-p8.iam.gserviceaccount.com \
            --worker-pool-spec=replica-count=1,machine-type=n1-standard-4,container-image-uri=gcr.io/sixth-utility-449722-p8/house-price-training:latest \
            --args="--project=sixth-utility-449722-p8,--region=us-central1,--model-dir=gs://housing-data-bucket-poc/model_registry/"