name: XGBoost Model Training and Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  train_and_deploy:
    name: "Train and Deploy XGBoost Model"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: sixth-utility-449722-p8

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install xgboost numpy scikit-learn

      - name: Train XGBoost Model
        run: |
          python train_xgboost.py

      - name: Upload Model to GCS
        run: |
          gsutil cp model.bst gs://housing-data-bucket-poc/model_registry/

      - name: Upload Model to Vertex AI Model Registry
        run: |
          gcloud ai models upload \
            --region=us-central1 \
            --display-name=house-price-xgb-model \
            --container-image-uri=us-docker.pkg.dev/vertex-ai/prediction/xgboost-cpu.1-3:latest \
            --artifact-uri=gs://housing-data-bucket-poc/model_registry/

      - name: Create Vertex AI Endpoint
        run: |
          gcloud ai endpoints create \
            --region=us-central1 \
            --display-name=house-price-endpoint

      - name: Deploy Model to Vertex AI Endpoint
        run: |
          MODEL_ID=$(gcloud ai models list --region=us-central1 --filter="displayName=house-price-xgb-model" --format="value(name)" | head -n 1)
          ENDPOINT_ID=$(gcloud ai endpoints list --region=us-central1 --filter="displayName=house-price-endpoint" --format="value(name)" | head -n 1)

          echo "MODEL_ID: $MODEL_ID"
          echo "ENDPOINT_ID: $ENDPOINT_ID"

          gcloud ai endpoints deploy-model $ENDPOINT_ID \
            --region=us-central1 \
            --model=$MODEL_ID \
            --display-name=house-price-xgb-deployment \
            --machine-type=n1-standard-4 \
            --min-replica-count=1 \
            --max-replica-count=1